### ISSUE TITLE
Mount capabilities for unpriviledge users

### ISSUE THREAD

**Issue by dyamon** [pop-os/sys-mount#20]
Is it possible to use this library to somehow grant unpriviledge users the ability to mount arbitrary filesystems (not necessarily in fstab), similar to what `pmount` does?

**Comment by mmstick** [comment]
No, this library only provides a wrapper for the mount system call. You could use it to create a `pmount`-like application though.

The reason `pmount` works as it does because it is a `setuid` binary. When an unprivileged user executes this binary, the binary changes the uid of the caller to the owner of the binary, thereby escalating itself to root privileges. It's essentially `sudo mount` but without a password requirement to get root privileges.

**Comment by dyamon** [comment]
Thanks for the nice explaination. I'll look into this.
